name: Build and Create Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build the application
      run: dotnet build --configuration Release

    - name: Install NSIS
      run: choco install nsis -y

    - name: Create Installer
      run: |
        makensis /V3 /DOutFile=LogvideoRecorder_Installer.exe installer.nsi

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: LogvideoRecorder_Installer
        path: LogvideoRecorder_Installer.exe
      
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Installer to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./LogvideoRecorder_Installer.exe
        asset_name: LogvideoRecorder_Installer.exe
        asset_content_type: application/octet-stream        